<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Blazored.FluentValidation" Version="2.2.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\" />
    <Folder Include="Requestses\Sales\" />
    <Folder Include="Requestses\Product\" />
    <Folder Include="Validations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysproAssigment.Shared\SysproAssigment.Shared.csproj" />
  </ItemGroup>

</Project>
